name: Tests

on:
  pull_request:

jobs:
  changelog:
    if: ${{ github.base_ref == 'develop'  || contains(github.base_ref, 'release-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - run: pip install towncrier==19.2.0
      - run: scripts/check-newsfragment
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}